### ISSUE TITLE
CS UWP Sample does not work

### ISSUE THREAD

**Issue by cra0zy** [Vungle/Windows-SDK#15]
C# UWP sample in this repo does not work, the initialization does occur, but that's all that does, you can't get any ad to load up.

Also an extra note, if I follow your tutorial in the README [1], I get an index out of range when I call Play.

[1] https://support.vungle.com/hc/en-us/articles/211339368-Get-started-with-Vungle-Windows-SDK

**Comment by DavidKimVungle** [comment]
The previous commit seems to have broken the reference link to the project and also the README had legacy integration documentation linked to it. 6.2.0 branch has the latest SDK and I confirmed it to be working properly.

6.2.0 Branch - https://github.com/Vungle/Windows-SDK/tree/6.2.0
Integration Documentation - https://support.vungle.com/hc/en-us/articles/360003059331

**Comment by cra0zy** [comment]
The 6.2.0 branch seems to be working, thanks!

PS. For anyone trying to use their own placement ids, make sure "Cached" is checked on your placements profile page.

**Comment by Moreno-Borsalino** [comment]
I can't access Integration Documentation - https://support.vungle.com/hc/en-us/articles/360003059331
because ask to sign in. But I am already registered and credential fails.
Why can't read that page ?

**Comment by gregthatcher** [comment]
Sorry to hear about the problems you are having.

We have been updating our docs recently, and we've apparently created some
permission problems.

Can you please try again at
https://support.vungle.com/hc/en-us/articles/360003059331-Integrate-Vungle-SDK-for-Universal-Windows-Platform-UWP

Thanks,
Greg

**Comment by Moreno-Borsalino** [comment]
Yes, the link works now. Thanks!
