### ISSUE TITLE
WPF support either as a future addition or via XAML Island?

### ISSUE THREAD

**Issue by mentorfloat** [Vungle/Windows-SDK#27]
Vungle only targets UWP right now, but there is a vast number of apps that are still in WPF due to how robust the platform is. 

Is there a way to integrate Vungle SDK into a WPF app?

There is a method to create custom UWP controls via [XAML Island](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands) in WPF. Is that an option that was explored? If so, do you have examples?

**Comment by mentorfloat** [comment]
For more context, trying to host MainPage.xaml from the CS_sample via XAML Island in a WPF app will not get past SDK initialisation.

The VungleAdControl blank containers will load but clicking the button to obtain Vungle SDK instance will throw the following exception:
```
The type initializer for 'VungleSDK.shared.CrossCuttingConcerns.PersistentSettings' threw an exception.
at VungleSDK.shared.CrossCuttingConcerns.PersistentSettings.SetString(String propertyName, String value)
at VungleSDK.shared.CrossCuttingConcerns.PersistentSettingsBase.GetSdkVersion(String sdkVersion, String ns, String currentVersion)
at VungleSDK.StandardEnvironment.get_NeedCleanup()
at VungleSDK.AdFactory.GetInstance(String appID, VungleSDKConfig config)
```
With this inner exception:
```
The process has no package identity. (0x80073D54)
at Windows.Storage.ApplicationData.get_Current()
at VungleSDK.shared.CrossCuttingConcerns.PersistentSettings..cctor()
```

**Comment by gregthatcher** [comment]
Hi mentorFloat,

Yes, this is something we are currently trying to implement (Vungle for WPF).  We are trying to make a new SDK specifically targeted for WPF.  We have already solved the "package identity" problem you mentioned above, but still have a number of things to work out (LocalSettings, File access, WebView, etc.).  

Please let us know if you would be interested in being a beta tester.  If yes, please email us at support (at) vungle.com and also greg.thatcher (at) vungle.com.  

Thanks much,
Greg Thatcher

**Comment by mentorfloat** [comment]
Hi Greg, thanks for the notice. We can continue our conversation on email and close this Github issue.
