### ISSUE TITLE
C# Winform VungleSDK 6.11.1 Installation Failure Inquiry

### ISSUE THREAD

**Issue by boardpen** [Vungle/Windows-SDK#46]
We are producing a program using C# winform.

When installing the Vungle SDK 
"Severe code description project file line display error (suppressed) status
Error Unable to install package 'VungleSDK 6.11.1'. I'm trying to install this package on a project targeting '.NETFramework, Version=v4.6.2', but there are no assembly references or content files compatible with that framework. Please contact the author of the package for more information."
There is an error.

Is there a way to solve it, or is there a sample code built using Winform?

**Comment by gregthatcher** [comment]
Hi @boardpen ,

Sorry for the delay in getting back to you.

We are creating a new SDK for WinForms.  The old SDK is made for UWP, and won't work for you.

Would you like to be a Beta tester?  If so, you can download our Beta version of the SDK at https://vungle2-sdk-dev-scratch.s3.amazonaws.com/windows/7.0/LiftoffSDK.WinForms.dll

There is some sample code that might help you at https://vungle2-sdk-dev-scratch.s3.amazonaws.com/windows/7.0/Demo+Apps/LiftoffWinFormsDemoApp.zip

Please let us know if this works for you, and let us know of any suggestions or problems that you have.

**Comment by boardpen** [comment]
> Hi @boardpen ,
> 
> Sorry for the delay in getting back to you.
> 
> We are creating a new SDK for WinForms. The old SDK is made for UWP, and won't work for you.
> 
> Would you like to be a Beta tester? If so, you can download our Beta version of the SDK at https://vungle2-sdk-dev-scratch.s3.amazonaws.com/windows/7.0/LiftoffSDK.WinForms.dll
> 
> There is some sample code that might help you at https://vungle2-sdk-dev-scratch.s3.amazonaws.com/windows/7.0/Demo+Apps/LiftoffWinFormsDemoApp.zip
> 
> Please let us know if this works for you, and let us know of any suggestions or problems that you have.

Sure, you can add me in your list

**Comment by boardpen** [comment]
대용량 첨부 1개 19MB

LiftoffWinFormsDemoApp.zip 19974191 ~ 2024/07/06
기한이 있는 파일은 30일 보관 / 100회 다운로드 가능



안녕하세요.

Visual Studio 2017 Windows Forms .NET Framework 4.6.2를 사용하고 있습니다.
전달해 주신 파일로 구동 하려고 하였으나 정상적으로 진행 되지 않아
다시한번 확인 요청 드립니다.

또한 Vungle를 사용하기 위해 App ID등을 입력을 어디에 해야하나요?


-----Original Message-----

**Comment by boardpen** [comment]
안녕하세요 승현님.
리프트오프 민선영입니다.

담장자에게 내용 전달하도록 하겠습니다.

감사합니다.
민선영 드림

@Hello Greg,

Thank you for your assistance.

The publisher is using Visual Studio 2017 Windows Forms .NET Framework
4.6.2.

They tried running it with the file you shared earlier in the thread but it
does not work properly.
Can you please check again?

Also, where do they need to apply the app id into?

Thank you!

Best,
Sun

Sunyoung Min | Liftoff | Sr. Account Executive | ***@***.*** | C:
010-3417-3768

**Comment by gregthatcher** [comment]
Hi @boardpen ,

Are you saying that you are having a problem integrating into your own app, or are you having a problem running the LiftoffWinFormsDemoApp?

I suggest you start with the demo app.  You will need to enter your app id into the "App ID" textbox of that app.   If you look at the source code for that app, (in FormMain.cs) you will see that it uses the application id on this line:
m_sdk = await LiftoffAds.InitializeAsync(<your app id>, sdkConfig);

Our SDK uses .Net 8.0, and we are using Visual Studio 2022.  Is it possible that you could upgrade your app?  We _may_ be creating an SDK using an earlier version of .Net (e.g. 4.7), so please let us know if this is something you would want.

Thanks,
Greg

**Comment by boardpen** [comment]
> Hi @boardpen ,
> 
> Are you saying that you are having a problem integrating into your own app, or are you having a problem running the LiftoffWinFormsDemoApp?
> 
> I suggest you start with the demo app. You will need to enter your app id into the "App ID" textbox of that app. If you look at the source code for that app, (in FormMain.cs) you will see that it uses the application id on this line: m_sdk = await LiftoffAds.InitializeAsync(, sdkConfig);
> 
> Our SDK uses .Net 8.0, and we are using Visual Studio 2022. Is it possible that you could upgrade your app? We _may_ be creating an SDK using an earlier version of .Net (e.g. 4.7), so please let us know if this is something you would want.
> 
> Thanks, Greg

HI @gregthatcher

.NETFramework, Version=v4.6.2에 사용할 수 있는 SDK를 제공해 주실 수 있나요?
Could you please provide me with the SDK available for .NETFramework, Version= v4.6.2?

Thanks,
boardpen

**Comment by gregthatcher** [comment]
Yes, we will try to make a 4.6.2 version.    We will _try_ to get you something by the end of July.  Let us know if that works for you.

**Comment by gregthatcher** [comment]
My apologies for the delays.  We are hoping to get a working version by the end of this month or beginning of October.

**Comment by gregthatcher** [comment]
Very sorry for all of the delays, but we finally have a working version of WinForms for .net 4.6.2

You can download the SDK here : https://vungle2-sdk-dev-scratch.s3.us-east-1.amazonaws.com/windows/7.0/LiftoffSDK.WinFormsLegacy.dll

You can download a sample app here : https://vungle2-sdk-dev-scratch.s3.us-east-1.amazonaws.com/windows/7.0/Demo+Apps/LiftoffWinFormsLegacyDemoApp.zip

Note that this SDK is still in Beta.  Please let us know if things work for you (or not).

**Comment by boardpen** [comment]
> 지연으로 인해 매우 죄송합니다. 마침내 .net 4.6.2용 WinForms의 작동 버전이 나왔습니다.
> 
> SDK는 여기에서 다운로드할 수 있습니다: https://vungle2-sdk-dev-scratch.s3.us-east-1.amazonaws.com/windows/7.0/LiftoffSDK.WinFormsLegacy.dll
> 
> 샘플 앱은 여기에서 다운로드할 수 있습니다: https://vungle2-sdk-dev-scratch.s3.us-east-1.amazonaws.com/windows/7.0/Demo+Apps/LiftoffWinFormsLegacyDemoApp.zip
> 
> 이 SDK는 아직 베타 상태입니다. 문제가 없는지(또는 없는지) 알려주세요.

Hello, gregthatcher
Windows ver is being tested.
The value of m_sdk seems to be not working due to null, so please check it.

'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\개인\SRC\C#\Winforms\LiftoffWinFormsLegacyDemoApp\LiftoffWinFormsLegacyDemoApp\bin\Debug\LiftoffWinFormsLegacyDemoApp.exe'. Symbols loaded.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'D:\개인\SRC\C#\Winforms\LiftoffWinFormsLegacyDemoApp\LiftoffWinFormsLegacyDemoApp\bin\Debug\LiftoffSDK.WinFormsLegacy.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
30-10 08:12:22.336 Info InitializeAsync Initializing .Net 4.6.2 (WinUI3/WinForms/WPF) 

'LiftoffWinFormsLegacyDemoApp.exe' (CLR v4.0.30319: LiftoffWinFormsLegacyDemoApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_ko_b77a5c561934e089\mscorlib.resources.dll'. Module was built without symbols.
30-10 08:12:22.416 Error InitializeAsync Exception System.IO.FileNotFoundException: 파일이나 어셈블리 'Microsoft.Web.WebView2.WinForms, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 파일을 찾을 수 없습니다.
파일 이름: 'Microsoft.Web.WebView2.WinForms, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e'
   위치: LiftoffSDK.Models.DeviceModels.DeviceInfo..ctor()
   위치: LiftoffSDK.CrossCuttingConcerns.AbstractFactories.VungleSdkConcreteFactory.CreateDeviceInfoController() 파일 C:\source\windows-sdk-dev-clone\LiftoffSDK\SDKs\LiftoffSDK\CrossCuttingConcerns\AbstractFactories\VungleSdkConcreteFactory.cs:줄 34
   위치: LiftoffSDK.CrossCuttingConcerns.InstanceManager..ctor(String nameSpace, IVungleSdkAbstractFactory abstractFactory) 파일 C:\source\windows-sdk-dev-clone\LiftoffSDK\SDKs\LiftoffSDK\CrossCuttingConcerns\InstanceManager.cs:줄 68
   위치: LiftoffSDK.Public.LiftoffAds.<InitializeAsync>d__18.MoveNext() 파일 C:\source\windows-sdk-dev-clone\LiftoffSDK\SDKs\LiftoffSDK\Public\LiftoffSdk.cs:줄 69

=== 미리 바인딩된 상태 정보 ===
로그: DisplayName = Microsoft.Web.WebView2.WinForms, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e
 (Fully-specified)
로그: Appbase = file:///D:/개인/SRC/C#/Winforms/LiftoffWinFormsLegacyDemoApp/LiftoffWinFormsLegacyDemoApp/bin/Debug/
로그: 초기 PrivatePath = NULL
호출 어셈블리: LiftoffSDK.WinFormsLegacy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
로그: 이 바인딩은 default 로드 컨텍스트에서 시작됩니다.
로그: 응용 프로그램 구성 파일 D:\개인\SRC\C#\Winforms\LiftoffWinFormsLegacyDemoApp\LiftoffWinFormsLegacyDemoApp\bin\Debug\LiftoffWinFormsLegacyDemoApp.exe.Config을(를) 사용합니다.
로그: 호스트 구성 파일 을(를) 사용합니다.
로그: C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config에서 컴퓨터 구성 파일을 사용합니다.
로그: 사후 정책 참조: Microsoft.Web.WebView2.WinForms, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e
로그: 새 URL file:///D:/개인/SRC/C#/Winforms/LiftoffWinFormsLegacyDemoApp/LiftoffWinFormsLegacyDemoApp/bin/Debug/Microsoft.Web.WebView2.WinForms.DLL을(를) 다운로드합니다.
로그: 새 URL file:///D:/개인/SRC/C#/Winforms/LiftoffWinFormsLegacyDemoApp/LiftoffWinFormsLegacyDemoApp/bin/Debug/Microsoft.Web.WebView2.WinForms/Microsoft.Web.WebView2.WinForms.DLL을(를) 다운로드합니다.
로그: 새 URL file:///D:/개인/SRC/C#/Winforms/LiftoffWinFormsLegacyDemoApp/LiftoffWinFormsLegacyDemoApp/bin/Debug/Microsoft.Web.WebView2.WinForms.EXE을(를) 다운로드합니다.
로그: 새 URL file:///D:/개인/SRC/C#/Winforms/LiftoffWinFormsLegacyDemoApp/LiftoffWinFormsLegacyDemoApp/bin/Debug/Microsoft.Web.WebView2.WinForms/Microsoft.Web.WebView2.WinForms.EXE을(를) 다운로드합니다.



m_sdk : null

**Comment by gregthatcher** [comment]
Hi @boardpen ,

Please try using NuGet to add the WebView2 NuGet package to your project.

**Comment by boardpen** [comment]
> 안녕@boardpen,
> 
> NuGet을 사용하여 프로젝트에 WebView2 NuGet 패키지를 추가해 보세요.

Thank you for your help.
Banner would like to ask if it is not possible to test.

**Comment by gregthatcher** [comment]
Are you asking if we support Banner ads?  Unfortunately, we do not currently support banners ads.  You should not use our dashboard to create a banner.

**Comment by boardpen** [comment]
> Are you asking if we support Banner ads? Unfortunately, we do not currently support banners ads. You should not use our dashboard to create a banner.

WPF conducted a test to support banner advertising.

Does Windows Forms not support it?

To connect to the app
Should I register as a Microsoft developer?

I have registered as a developer, but I didn't learn how to launch it, so please help me if you have a manual.
